### ISSUE TITLE
Import ts files in static.config.js in React Static typescript template

### ISSUE THREAD

**Issue by HuberttK** [react-static/react-static#1110]
### Reporting a bug?

After creating new React Static app with typescript template i can't import .ts files in static.config.js. The similar situation happens when i change my static.config.js to static.config.ts and i try import .ts file then i got an errror: 

```
=> File changed: /artifacts/react-static-browser-plugins.js
=> Updating build...
Failed to build! Fix any errors and try again!
multi /MY_PROJECT/node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js /MY_PROJECT/src/index.js
Module not found: Can't resolve '/MY_PROJECT/src/index.js' in '/MY_PROJECT/node_modules/react-static/node_modules'
```

### Environment

Latest version of react-static create with typescript template

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
2.  select typescript template
3.  Open static.config.js 
4. Try to import in static.config.js any .ts file 
5. npm start / yarn start -> error

1a. Rename static.config.js to static.config.ts
2.Try to import .ts file -> error
3b. npm start / yarn start -> error

### Expected Behavior

I should be able to import .ts files in static.config.js  or build app with static.config.ts

### Reproducible Demo

 react-static create

**Comment by sw-yx** [comment]
hi hubert - this is a known bug right now unfortunately with the recent move to v7.  (https://github.com/nozzle/react-static/pull/1097) i havent had time to dig into it but @tannerlinsley says he's implemented a fix that i dont have time to look into right now..

**Comment by andrezero** [comment]
Hi! @tannerlinsley I'm willing to help :-)

I had done some experiments a while ago, and I'm super excited about using react-static, but I want all my code to be in typescript.

**Comment by tannerlinsley** [comment]
To make this work, we need to come up with a way for the **typescript plugin** to:
- Load require hooks for typescript. Using something like `https://github.com/TypeStrong/ts-node`.
- Change the *default* entry to `src/index.ts`, but not override a user-defined entry option.

Those are pretty straight forward on their own, but due to the timing and order that plugins run, it is harder to get it to work from the typescript plugin itself. If that's the case, we may need to just include the hooks by default in the build and simply have the typescript template default to `index.ts`.

We'll see.

**Comment by andrezero** [comment]
I believe this is not a plugin responsibility. It's a matter of running react-static in a ts environment as you mentioned. It's about how to write your SSG code, leveraging existing libraries, data sources, etc...

So, the good news is: I just tried to launch react-static with ts-node and everything seems to be working fine. 

```
node -r ts-node/register node_modules/.bin/react-static  start
```

Then, from within `static-config.js` I am able to import typescript modules straight up.

```
import getRoutes from './src/routes';
```

For now, I'm just running the `basic` example converted to typescript. I will continue down this path and see if/where it breaks ;-)

**Comment by SleeplessByte** [comment]
> Load require hooks for typescript. Using something like https://github.com/TypeStrong/ts-node.

Please don't. `ts-node` is *not* equivalent to `tsc`, even though people think it is. It usually lags behind typescript releases. Using `babel` typescript (stripping types) ís an effort co-worked on by microsoft and could be used here.

The real issue is that the `typescript-plugin` is only laoded INSIDE this configuration. The real way to fix it, imo, is to add `tsconfig.json` to the project / load static.config.ts through babel or the likes -- and leave everything else the same.

**Comment by tannerlinsley** [comment]
@SleeplessByte You're right. I started down this path a while ago and it felt right, but got pulled away into other things before I could finish. Easier to reuse existing code paths and just make everything typescript aware the right way.

**Comment by andyfleming** [comment]
@SleeplessByte — `ts-node` only specifies typescript as a peer dependency so it doesn't limit which version of typescript you use (as far as I know). Similarly, I believe it will respect a `tsconfig.json` file if it's present.

**Comment by SleeplessByte** [comment]
Sure, but that's exactly it's problem. When TS is released, ts-node often accepts using the newer version but has bugs around it.

Anyway, in RS 8 this is all working and supported (for plugins, projects, config, and templates, out of the box).

**Comment by andyfleming** [comment]
Fair enough. Sounds good. 👍 

Is there a milestone or somewhere where RS 8 is being tracked?

**Comment by SleeplessByte** [comment]
Not yet. I'll make sure it's somewhere once I finished the `export` command, so that I know who to allocate building the rest / what it would take. It's mostly an internal rewrite, without too many "external"/public API changes.

This is what my static looks like in RS 8:

```typescript
// static.config.ts

import { AppConfig, RouteConfigList } from '@react-static/types'

const config: AppConfig = {
  data: { global: { my: 'data' } },
  routes: async (): Promise<RouteConfigList>  => {
    const items = [
      { data: 'example', id: 1 },
      { data: 'other', id: 2 },
    ]

    // Creates the /items route, and exposes ALL item data
    // Creates the /items/1 and /items/2 routes, and exposes a single item
    return [
      {
        path: '/items',
        data: { items },
        children: items.map((item) => ({
          path: `/${item.id}`,
          template: 'src/containers/Item',
          data: Promise.resolve(item),
        })),
      },
    ]
  },
  plugins: [
    [
      '@react-static/plugin-source-filesystem',
      {
        location: './src/pages',
      },
    ],
    '@react-static/plugin-reach-router',
    '@react-static/plugin-sitemap',
  ],
}

export default config
```

It also allows you to use `.jsx` and `.tsx`, because some plugins will allow you to pass in `React.ComponentType`.

We also encourage people to use the TypeScript variant, or at least turn on `// @ts-check`, because the types correctly accepts for example the following `data` values for routes:

```typescript
{
  data: { some: 'object' },
  data: Promise.resolve({ some: 'result of a promise' }),
  data: () => ({ some: 'function that returns an object' }),
  data: async () => ({ some: 'async function that returns an object' })
}
```

**Comment by danielgreane** [comment]
Hey @SleeplessByte , I was wondering where RS 8 was on the roadmap, does it have a release date, or a canary branch we can experiment with? 

I've tried using above recommendations to get the config file working in TS but struggled to get something streamline, am wondering whether or not to just wait until v8 or persist :-)

**Comment by kespindler** [comment]
For those still struggling with this:

1. `npm install --save ts-node`
2. Add the following line to the top of your `static.config.js` file (Note it must remain a js, not ts, file):

```
require('ts-node').register({
  compilerOptions: {
    module: 'commonjs',
    target: 'es2019',
  }
})
```

3. After that line, you can import `.tsx?` files using `require` (`import` doesn't seem to work):

```
const {getRoutes} = require('./src/route')
```

I hope that helps!
