### ISSUE TITLE
[FEATURE REQUEST]: Add ability to strip all react code (and routeInfo) from the exported html (per configured)

### ISSUE THREAD

**Issue by itchingpixels** [react-static/react-static#1212]
We're trying to optimise the size of the html (as we have hundreds of thousands of them) for a full-static website.

We'd love to have a flag that would stop embedding routeInfo and linking to any external js code.

Similarly to what happens when route.redirect is set - but applied for all pages.

We'd be happy to invest the time to implement this, but want to make sure that this is a feature that we'll manage to get merged before we spend the time making it production-ready.

Thanks!

**Comment by sw-yx** [comment]
i've no problem with this in principle, but its @tannerlinsley's call

**Comment by Pixelatex** [comment]
Agreed, it's tanner's call. But I am kinda wondering how your site will function properly if you strip all js and routeinfo from it... I think you're just using RS as a generic html generator.

This could prove problematic in future support as builds need to work without the core features attached to it :/

(unless I understood you incorrectly)

**Comment by sw-yx** [comment]
you can strip js, it will fall back to raw links, however routeinfo may be problematic.

**Comment by Pixelatex** [comment]
Maybe instead of removing it, it would be more beneficial to create a 'lite' version for massive low-performance sites?

**Comment by JoseFMP** [comment]
@Pixelatex 

I think both possibilities would be interesting, a _lite_ version as well as to remove the whole react scripts and route info.

And to answer your concern above, of this causing the site to be totally stateless ---> this is exactly the set-up we are interested in, and that's why we are so interested in removing the `routeInfo` and imports of JS in our site: For our current set-up they are only waste. Waste of disk space, longer upload times, etc.

**Comment by bloudermilk** [comment]
We're also interested in this. Ultimately we like react static because it's fast/simple and React is familiar. However we don't need code splitting or any client-side JS as we're just generating simple content pages. We'd love to turn off JS entirely on export!

**Comment by Pixelatex** [comment]
I understand your request but what you essentially want is a plain html generator then... For me, this feels like going out of scope of what RS does. It might be a lot better to create a simple js templating system to generate this. 

I'm also worried about a lot of confusion this might cause, you can write react but... in reality, you'll be stripping it out so I can already see people posting a ton of issues about stuff not working on their build...

**Comment by bloudermilk** [comment]
> It might be a lot better to create a simple js templating system to generate this.

Actually, this is what we're trying to avoid and why we chose RS over other frameworks. On paper, something like Hugo would be a better choice for us since we're just looking to output static HTML. But then we have to learn their templating system and frankly, a pretty complex framework.

It's fair to consider if deployments like this are within the scope of the project or not, and I don't know the project well enough to understand the ambitions. But to me, this seems like a pretty straightforward opt-in feature. Keeping all else the same, just don't include the JS in the generated output. My assumption was that since the app is progressive already, everything should "just work" without it.

**Comment by itchingpixels** [comment]
By the way, we resolved this by writing a plugin that strips out the unnecessary code.

**Comment by sw-yx** [comment]
hi everyone! thanks for your issue! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by SleeplessByte** [comment]
@itchingpixels such a plugin we'll happily support! Let me know if you want to add it officially. It seems that others might benefit also.
