### ISSUE TITLE
[Plugin] Sitemap hreflang

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1273]
Hey guys,

The old issue https://github.com/react-static/react-static/issues/986 regarding the generation of hreflang in the sitemap has been closed when the v7 plugin came out but I'm still unsure how to proceed to implement it?

The plugin doc shows that it's possible to have custom xml tags but it doesn't show if it's possible to add attributes on these tags.

Any thoughts?

**Comment by deiga** [comment]
@ugogo Did you ever solve this?

I've been trying out some combinations, but ultimately the plugin code looks like it doesn't support creating XML elements with attributes. 
And since the config is done via JS Objects it doesn't allow duplicate keys, which kind of kills the possibility of adding hreflang links, since you need always at least 2 when adding them

**Comment by ugogo** [comment]
Unfortunately no @deiga, sorry 😶
