### ISSUE TITLE
[Bug] Preact plugin seems to not work

### ISSUE THREAD

**Issue by jurosh** [react-static/react-static#1331]
### Reporting a bug?

Trying to use preact plugin - https://github.com/react-static/react-static/tree/master/packages/react-static-plugin-preact

But even after including `preact` in plugins, there is no difference to bundle size. Still `analyze` display around 400kB for `react` & `react-dom`, and it should be around 3kB for `preact`.

![image](https://user-images.githubusercontent.com/1630137/67478604-a8260980-f65c-11e9-8f47-d6ad294260c7.png)

### Environment

```
System:
    OS: Ubuntu 19.10
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v11.14.0/bin/npm
  npmPackages:
    react-static: ^7.2.2 => 7.2.2 
    react-static-plugin-preact: ^7.2.2 => 7.2.2 
    react-static-plugin-reach-router: ^7.2.0 => 7.2.2 
    react-static-plugin-sitemap: ^7.2.0 => 7.2.2 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.2.2
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  add preact plugin
2.  run `yarn analyze`
3.  see that react is there

**Comment by SleeplessByte** [comment]
It currently only applies preact in production, or so it seems:

https://github.com/react-static/react-static/blob/master/packages/react-static-plugin-preact/src/node.api.js#L3

**Comment by SleeplessByte** [comment]
If you'd like this to work in dev too, we accept a PR. It won't be a bug but a new feature :)

**Comment by tbgse** [comment]
@SleeplessByte I know this issue has long been closed but i'm seeing the same problem even after creating a custom plugin with the same preact replacement code without the `dev` condition:

Also following the original issue above, wouldn't `yarn analyze` create a production bundle where the original plugin should've been applied? Very curious if @jurosh ever found a solution to it.

here is my plugin code:

```
export default () => ({
  webpack: (config, { stage }) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      react: 'preact-compat',
      'react-dom': 'preact-compat',
    }
    
    return config
  },
})
```

in `plugins/custom-preact/node.api.js`

it seems to me that the webpack alias is never being applied (but i see the plugin running during the build). I'd really appreciate if someone else could have a quick look, if this is maybe just an error on my end or if there is indeed something else going on.

**Comment by tbgse** [comment]
I added some logging to the file in `react-static` that creates the full webpack config and found this:
```
    alias: {
      'react$': '/mnt/c/dev/react-static-ts/node_modules/react/index.js',
      'react-dom$': '/mnt/c/dev/react-static-ts/node_modules/react-dom/index.js',
      'react-universal-component': '/mnt/c/dev/react-static-ts/node_modules/react-universal-component/dist/index.js',
      __react_static_root__: '/mnt/c/dev/react-static-ts',
      react: 'preact/compat',
      'react-dom': 'preact/compat',
      components: '/mnt/c/dev/react-static-ts/src/components',
      containers: '/mnt/c/dev/react-static-ts/src/containers',
      types: '/mnt/c/dev/react-static-ts/types'
    }
```

note that there are references to `react$` and `react-dom$` which are still pointing to react instead of preact. Changing my plugin to reference worked:

```
      'react$': 'preact/compat',
      'react-dom$': 'preact/compat',
```

See bundle here: https://gyazo.com/db2c702d277ae4bbca81acc4313773f2


I could open a PR to make these changes to the react plugin and also update it to use the latest version of preact which at least for us so far seems to work fine with react-static.

**Comment by SleeplessByte** [comment]
I would _love_ a PR. nice catch ❤️

**Comment by tbgse** [comment]
This actually became an even larger piece of work, because i'm trying to work in preact prefresh (https://github.com/JoviDeCroock/prefresh) as replacement for react-hot-loader since the two are not compatible. 

The work for that extends a bit beyond the plugin to also make some adjustments to the index files to get rid of the react specific code. I know it'd be an option to just swap react to preact for production but in my experience that can be quite risky. We've had situations before where small quirks of preact were causing problems that we would only have caught in production if we worked with react during development. 

So far I've managed to get the dev sever running fine while preserving state on changes in the components, but whenever i make changes to the getRoutes, the dev server seems to freeze. Still digging through the code to figure out why and where this is happening, but I'm suspecting some other reference to tied to react-hot-reload somewhere in the logic that runs when updating routes. (If you have a hunch, let me know)

How should I go about creating a PR for this once I'm done? Since these changes to some starter files are required, creating a PR for a plugin won't really cut it, if we want it to work out of the box. I guess we could always add some instructions in the readme?

**Comment by SleeplessByte** [comment]
Docs + plugin PR + base code if necessary. PRs here don't need to be scoped to a single package. We've had quite a few, also by the great `nddery` (not tagging so they don't get notified unnecessarily) that span multiple packages.

I agree that having it work during development is a great idea.

So for the freezing part: 

I don't think we configure RHL (which we should dump now that there is React Refresh, but no time to do this right now) to do something special on change client routes. All we do is send a message via the web-socket to "reload". 

However, it might be in the webpack dev server setup.
