### ISSUE TITLE
Need an actual web site for docs, and getting started tutorial

### ISSUE THREAD

**Issue by krishnasaga** [react-static/react-static#1334]
Need an actual web site for docs, and getting started tutorial

Why ?
https://www.npmtrends.com/react-static-vs-gatsby

**Comment by Pixelatex** [comment]
We used to have one but tanner removed it I think because keeping them in sync wasn't easy.

I however agree that we could use a simple documentation site.

**Comment by gryzzly** [comment]
Yes, the beginner experience is now entirely broken, lots of 404 links linked from various places. Entirely unclear how to handle simplest things :( (as compared to previous folder of examples)

**Comment by SleeplessByte** [comment]
This is all in place for the next major. I find docs very important.

**Comment by Zauberfisch** [comment]
bump. 

I am currently evaluating react-static and other react static site generators. From what I can see so far, react-static wins me over in many key decitions/concepts. But, despite hating parts of gatsby, I might still go for gatsby.

From an outside perspective (at least at first glance), react-static looks inactive and unmaintained because of missing/broken docs, links to a spectrum community that doesn't exist, no examples, ...

**Comment by SleeplessByte** [comment]
Do whatever is best for you. 

Spectrum was moved to GitHub discussions.

**Comment by Zauberfisch** [comment]
I realise that spectrum was moved to github. The point is that the readme still mentions spectrum prominently as the place to chat and get support.
