### ISSUE TITLE
[Docs] Add Facebook Comments with React-Static

### ISSUE THREAD

**Issue by PolMrt** [react-static/react-static#1416]
Hello,

I'm trying to add facebook comments plugin with [react-facebook](https://github.com/seeden/react-facebook) but it seems that it doesn't work with react-static. Indeed, the script seems to not be required anymore when building the app.

Is there a way to add Facebook Commment plugin with react-static ?

Thanks,

**Comment by SleeplessByte** [comment]
The problem is probably that `react-facebook` is adding a script to the `document`, which is not supported like that. You could do one of two things:

1. Conditionally require it, by checking `typeof document !== 'undefined'` and then `require('react-facebook')`. The "else" branch should be a simple pass-through component.
2. Don't use `react-facebook` and use `<Head />` (`react-helmet`) instead because that _will_ work with SSR.

However, this is not a support forum for other libraries. I suggest you try getting more help on either Spectrum or StackOverflow. If you figure this out, we do appreciate a PR to update the documentation.
