### ISSUE TITLE
Make static route data synchronously available & applicable at SSR stage

### ISSUE THREAD

**Issue by strogonoff** [react-static/react-static#1471]
**Is your feature request related to a problem? Please describe.**

Currently, using route data requires waiting for the page to load and JS to execute.

If I, say, `useLocation()` to e.g. set active navigation link in bold, it will not be bold in HTML returned from the server. Anywhere I use route data it hides behind suspense.

Which seems to make little sense, since at site generation stage we _know_ full route data for the page being generated (dynamic routes aside).

**Describe the solution you'd like**

Pass route data to each page component as props?

**Describe alternatives you've considered**

Workaround would be different depending on how and where exactly I want to `useRouteData()`, involving putting corresponding case-specific logic in `getRoutes()`.

(E.g., for highlighting navigation items I could generate a different nav structure for each route, almost the same but with “is active” flag set on particular nav item).

**Additional context**

EDITED: I think I was confusing external route location data (e.g. from reach route) and react-static’s own route data. The latter does seem to be available statically. Don’t know if this ticket still makes any sense.

**Comment by SleeplessByte** [comment]
Yes, `useRouteData` is always available without suspense. I'd like to change [`onLocationChange`](https://github.com/react-static/react-static/blob/master/packages/react-static/src/browser/utils/onLocationChange.js) and [`useLocation`](https://github.com/react-static/react-static/blob/master/packages/react-static/src/browser/hooks/useLocation.js) so that it knows the location statically, which can probably be achieved if we take the "root url" + current SSR path.

**Comment by Zauberfisch** [comment]
> Yes, useRouteData is always available without suspense

@SleeplessByte is that information still up2date? when I place a `useRouteData` outside of a suspense, I got two different errors:

When outside of suspense but inside of a react context I get the following error on build:
```
ReactDOMServer does not yet support Suspense.
```

When outside of suspense and outside of my state context, the build is fine, and staticly served html is fine, but after page navigation I get:

```
Error: h suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
```

--- 

As for getting the current route reliably, I've come up with the following: 
```
	const browserLocation = useLocation();
	const ssrLocation = useStaticInfo();
	const location = browserLocation ? useRoutePath(browserLocation.pathname) : ssrLocation.path;
```
which will make `location` contain the current path, regardless if it's ssr or browser.   
But I'd like to talk about possibly implementing that as a built-in method of react-static

**Comment by SleeplessByte** [comment]
Are you using preact by any chance?

**Comment by Zauberfisch** [comment]
no, node v14.12

**Comment by SleeplessByte** [comment]
preact and node are apples and oranges.

The reason I'm asking is because the error message says `h`, which is a function used in preact.

Either way, I don't completely understand what you're doing at the moment (Sorry! I've not been able to work on this due to COVID), but what you're proposing seems interesting.

`useRouteData` needs to be called inside the root or routes component (don't know which one by heart) and I think _that_ component adds our version of Suspense, which means you don't need to add it yourself.

In production, Suspense is replaced by a regular component; the routeinfo is placed _inline_ and in a file routeInfo.json. When a URL.is preloaded, that file is fetched and stored in memory. I don't think it ever requires Suspense, because suspense doesn't work during the build/export step.

During development, the routeinfo is server from the Webpack Dev Server.

**Comment by Zauberfisch** [comment]
sorry, I accidentally sent the message to quickly with the sentence not finished. 

Thanks for the input, I'll try and dig some more into it.
