### ISSUE TITLE
[Docs] Migrationg from Create React App

### ISSUE THREAD

**Issue by mukarramali** [react-static/react-static#1545]
I can't find any documentation to help migrate the existing create-react-app.
https://github.com/react-static/react-static/issues/1492 There is already an issue for the same, but it was closed without any explanation.

**Comment by augustosamame** [comment]
I agree this is the use case of many devs out there. I for one, got frustrated by my React app's lack of speed and want to take "snapshots" of certain routes so as to speed things up. This project seems like a perfect match, but I wouldn't know where to start to convert our huge and complex React app to react-static, just some routes at a time.

**Comment by alxndr** [comment]
I'm also curious about this — attempting to add `react-static` to a SPA made with `create-react-app` (unejected). 

My eventual goal is to use `react-router-dom`'s `BrowserRouter` in the app, so that a user of the site sees "normal" looking URLs (i.e. not containing `#?`, used by the `HashRouter`), and the site can be hosted on GitHub Pages (i.e. a static file is created for each desired URL and stored in the `public` subdirectory), and the HTML payloads for each desired URL can be indexed by search engines without evaluating JavaScript (i.e. with "normal" HTML DOM rather than SPA-container `index.html`)

**Comment by SleeplessByte** [comment]
There isn't really a guide to convert a `create-react-app` to a `react-static` app, because the two are very different, but more so because it completely depends on how your CRA was written in the first place.
